// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: tutorial.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TutorialServiceClient is the client API for TutorialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TutorialServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type tutorialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTutorialServiceClient(cc grpc.ClientConnInterface) TutorialServiceClient {
	return &tutorialServiceClient{cc}
}

func (c *tutorialServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/TutorialService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TutorialServiceServer is the server API for TutorialService service.
// All implementations must embed UnimplementedTutorialServiceServer
// for forward compatibility
type TutorialServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTutorialServiceServer()
}

// UnimplementedTutorialServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTutorialServiceServer struct {
}

func (UnimplementedTutorialServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTutorialServiceServer) mustEmbedUnimplementedTutorialServiceServer() {}

// UnsafeTutorialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TutorialServiceServer will
// result in compilation errors.
type UnsafeTutorialServiceServer interface {
	mustEmbedUnimplementedTutorialServiceServer()
}

func RegisterTutorialServiceServer(s grpc.ServiceRegistrar, srv TutorialServiceServer) {
	s.RegisterService(&TutorialService_ServiceDesc, srv)
}

func _TutorialService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorialServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TutorialService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorialServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TutorialService_ServiceDesc is the grpc.ServiceDesc for TutorialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TutorialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TutorialService",
	HandlerType: (*TutorialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _TutorialService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tutorial.proto",
}
